id: P787C8A4D
initial_creation_type: ocr
source_metadata:
  volumes:
    c349476f931944a7b0a83379f1297291:
      base_file: v057.txt
      image_group_id: I1PD95902
      title: དབུ་མ་རྩ་བའི་འགྲེལ་པ་ཤེས་རབ་སྒྲོན་མ།
      total_pages: 1605
      volume_number: 57
